name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-unix:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - ubuntu
        - macOS
        go:
        - 17
        - 18
    name: '${{ matrix.platform }} | 1.${{ matrix.go }}.x'
    runs-on: ${{ matrix.platform }}-latest
    steps:

    - uses: actions/setup-go@v3
      with:
        go-version: 1.${{ matrix.go }}.x

    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-1.${{ matrix.go }}.x-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-1.${{ matrix.go }}.x-

    - name: Install dependencies
      run: |
        export GOBIN=$HOME/go/bin
        case "${{ matrix.go }}" in
          17|18) _version='@latest';;
          *) _version='';;
        esac
        go install github.com/kyoh86/richgo"${_version}"

    - name: Test
      run: RICHGO_FORCE_COLOR=1 PATH=$HOME/go/bin/:$PATH richgo test -v ./...

    - name: Test Race
      run: RICHGO_FORCE_COLOR=1 PATH=$HOME/go/bin/:$PATH richgo test -v -race ./...

    # - name: Test GoCommandAll
    #   run: RICHGO_FORCE_COLOR=1 PATH=$HOME/go/bin/:$PATH richgo test -run TestGoCommandAll -gocommand-all

  test-win:
    strategy:
      fail-fast: false
      matrix:
        go:
        - 18
    name: 'windows | 1.${{ matrix.go }}.x'
    runs-on: windows-latest
    steps:

    - uses: actions/setup-go@v3
      with:
        go-version: 1.${{ matrix.go }}.x

    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-${{ matrix.go }}-

    - name: Test
      run: go test -v ./...

    - name: Test Race
      run: go test -v -race ./...
