name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        go: ['1.17', '1.18']
    name: Test Go ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build ./...

    - name: Test
      run: go test ./...

    - name: Test Race
      run: go test -race ./...
